### PR TITLE
Add tl api

### PR DESCRIPTION
**Pull request by wistefan**

### CODE REVIEW

**Comment by dwendland** [comment]
Maybe one could add a comment in the https://github.com/FIWARE/ishare-satellite/blob/add-tl-api/doc/certs/README.md stating that this config/doc is for Mac, and the *.cnf-linux files should be used on plain Linux?

**Review by dwendland — APPROVED** [review]

**Comment by wistefan** [comment]
> Maybe one could add a comment in the https://github.com/FIWARE/ishare-satellite/blob/add-tl-api/doc/certs/README.md stating that this config/doc is for Mac, and the *.cnf-linux files should be used on plain Linux?

Yes, I forgot that I also added them:)

**Review by dwendland — APPROVED** [review]

**Comment by dwendland** [comment]
Could you add some tests for the new endpoints? https://github.com/FIWARE/ishare-satellite/tree/main/tests/pytest

**Comment by wistefan** [comment]
> Could you add some tests for the new endpoints? https://github.com/FIWARE/ishare-satellite/tree/main/tests/pytest

done

**Pull request merged**
